version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: bijuliyatra-mysql
    ports:
      - "3306:3306"  # DBeaver 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}       
      MYSQL_DATABASE: evchargerdb   #  DB
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: bijuliyatra-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/evchargerdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build: ./frontend
    container_name: bijuliyatra-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  payment:
    build: ./payments-service
    container_name: bijuliyatra-payment
    ports:
      - "3001:3001"
    env_file:
      - ./payments-service/.env
    depends_on:
      - backend

volumes:
  mysql_data:
